server:
  port: 8006

spring:
  application:
    name: cloud-payment-com.customer.springcloud.service
  cloud:
    consul:
      # 指定 consul 的端口
      port: 8500
      # 指定 consul 的地址
      host: localhost
      discovery:
        hostname: localhost
        # com.customer.springcloud.service-name 为 consul 管理的 服务名， 可以通过 com.customer.springcloud.service-name 进行微服务调用，而不用使用地址和端口
        # com.customer.springcloud.service-name 注册之后，自己也可以发现
        service-name: cloud-consul-payment-com.customer.springcloud.service
