server:
  port: 8004
spring:
  application:
    name: cloud-payment-com.customer.springcloud.service
  cloud:
    zookeeper:
      # 配置要连接的 zookeeper 的 地址和端口
      connect-string: 192.168.211.133:2181
