server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 设置 OpenFeign 客户端 默认超时时间(OpenFeign 默认支持 Ribbon)
ribbon:
  # 建立连接后从服务端读取到信息所需要的时间
  ReadTimeout: 5000
  # 建立连接所需要的时间，适用于网络正常的情况下，两端连接所需要的时间
  ConnectTimeout: 5000

# 开启 OpenFeign 声明式接口的调用 日志级别为 debug
logging:
  level:
    com.customer.springcloud.service.OrderService: debug
