server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        # 设置配置文件存在的地址
        git:
          # uri 只可以使用 https 的方式获取，而不能使用 ssh 的方式获取
          uri: https://github.com/Zhangzichaozzc/microservicecloud-config.git
          #          search-paths: microservicecloud-config.git
          default-label: master
  # 添加 rabbitmq 配置， Spring Cloud Bus 是使用 RabbitMQ 的广播来同步配置 Config Client 端的属性的
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.211.170
    port: 5672

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 暴露 bus 刷新配置的节点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
