server:
  port: 80

eureka:
  instance:
    instance-id: ${spring.application.name}:80
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1


info:
  company.name: customer
  project.name: ${spring.application.name}