server:
  port: 8001

spring:
  application:
    name: cloud-payment-com.customer.springcloud.service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#      defaultZone: http://eureka7002.com:7002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    # Eureka Client 向 Eureka Server 发送心跳的时间, 默认 30 秒
#    lease-renewal-interval-in-seconds: 1
    # Eureka Server 在收到最后一次心跳后等待的时间上限(默认是90秒), 超时将剔除服务
#    lease-expiration-duration-in-seconds: 2

info:
  company.name: customer
  project.name: ${spring.application.name}:${server.port}

