server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8
  # 设置 监控信息 web地址
  zipkin:
    base-url: http://localhost:9411
  # 设置全链路 追踪的采样率
  sleuth:
    sampler:
      probability: 1

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

info:
  company.name: customer
  project.name: ${spring.application.name}:${server.port}