server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        # 路由的id，没有固定规则，但要求唯一，建议配合服务名使用
        - id: paymentroute${random.uuid}
          # 提供服务的路由地址
          #          uri: http://localhost:8001
          # 以服务名的方式路由请求，可以实现负载均衡
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/payment/**
            - After=2020-03-17T11:58:14.358+08:00[Asia/Shanghai]
#            - Before=2020-03-20T11:58:14.358+08:00[Asia/Shanghai]
#            - Between=2020-03-18T11:58:14.358+08:00[Asia/Shanghai],2020-03-20T11:58:14.358+08:00[Asia/Shanghai]
#            - Cookie=username,tom
#            - Header=X-Request,\d+
        - id: paymentroute2${random.uuid}
          #          uri: http://localhost:8001
          # 注意: 在配置以 注册中心中服务名进行路由的时候需要加前缀 lb:
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/ping/**
      # 开启路由发现服务的功能，开启后就可以通过在Eureka 中注册的服务名来实现负载均衡
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}