server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                username: guest
                password: guest
                host: 192.168.211.170
                port: 5672
      bindings:
        # 这里的 input 是一个 SubscribableChannel 的 beanName, 已经在容器中注册了
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbitmq
          # 将两个消费者 都放在同一个 group 中，可以避免同一个应用的多个实例重复消费问题
          group: customerA

eureka:
  instance:
    instance-id: receive-8802.com
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

